name = "generator"
description = "match generator for libadalang - developers only"
version = "0.0.0"

authors = ["Pierre van de Laar"]
maintainers = ["Pierre van de Laar <pierre.van.de.laar@gmail.com>"]
maintainers-logins = ["pjljvandelaar"]

executables = ["main_generator"]

[[depends-on]]
libadalang = "^22.0.0"
rejuvenation = "*"

[[pins]]
rejuvenation = { path = ".." } 
